https://qs100371.vip/douban-movies-nowplaying/douban_hot_movies.html

name: Deploy Douban Movies

on:
  schedule:
    - cron: '0 16 * * *'  # 北京时间每天0点（UTC 16:00）
  workflow_dispatch:      # 允许手动触发
  push:
    branches: [ main ]   # 推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 必需：写入权限

    steps:
      # 步骤1：检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 步骤2：设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 步骤3：安装依赖
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytz  # 时区支持

      # 步骤4：运行爬虫脚本（生成HTML）
      - name: Generate HTML
        run: python main.py

      # 步骤5：部署到GitHub Pages
     - name: Create deploy branch if not exists
        run: |
          if ! git ls-remote --heads origin | grep -q "gh-pages"; then
            git checkout --orphan gh-pages
            git rm -rf .
            echo "Initial commit" > index.html
            git add index.html
            git commit -m "Initial gh-pages commit"
            git push origin gh-pages
            git checkout main
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          force_orphan: true  # 确保每次都是干净部署
